---

- name: jekyll | create site root directory
  become: yes
  become_user: "{{ jekyll_build_owner }}"
  file:
    state: directory
    dest: "{{ jekyll_build_sourcedir }}"
    owner: "{{ jekyll_build_owner }}"
    mode: 0755
    serole: _default
    setype: _default
    seuser: _default

- name: jekyll | clone site source code repository
  become: yes
  become_user: "{{ jekyll_build_owner }}"
  git:
    repo: "{{ jekyll_build_git_repo }}"
    version: "{{ jekyll_build_git_branch | default(omit) }}"
    dest: "{{ jekyll_build_sourcedir }}/{{ jekyll_build_git_repo | basename }}"
    force: "{{ jekyll_build_force_git }}"

- name: install bundler
  gem: 
    name: bundler
    version: "{{bundler_version}}"

- name: update bundle
  become: yes
  command: bundle install
  args:
    chdir: "{{jekyll_build_sourcedir}}/{{jekyll_directory}}"
    removes: "{{jekyll_build_sourcedir}}/{{jekyll_directory}}/Gemfile"

- name: jekyll build
  command: bundle exec jekyll build
  environment:
    LC_ALL: "en_US.UTF-8"
  args:
    chdir: "{{ jekyll_build_sourcedir }}/{{ jekyll_directory }}"
